services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=hospital_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=hospital_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_db"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: